version: '3'

services:
  nginx:
    image: nginx:1.15.10-alpine
    ports:
      - 8000:80
    volumes:
      - ./status_files:/opt/status_page/status_files
      - ./nginx.conf:/etc/nginx/nginx.conf

  status:
    image: tschaerni/static-status:latest
    volumes:
      - ./status_files:/opt/status_page/status_files
